// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RastreoFirplak.Infrastructure.Persistence;

#nullable disable

namespace RastreoFirplak.Infrastructure.Migrations
{
    [DbContext(typeof(EnviosDbContext))]
    partial class EnviosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RastreoFirplak.Domain.DocumentoEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("FechaDespacho")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuiaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaEntrega")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuiaId");

                    b.ToTable("DocumentosEntregas");
                });

            modelBuilder.Entity("RastreoFirplak.Domain.DocumentoPOD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GuiaId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuiaId");

                    b.ToTable("DocumentoPODs");
                });

            modelBuilder.Entity("RastreoFirplak.Domain.Guia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Correotransportador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FH_CentroDestino")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FH_CentroOrigen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FH_Entregado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FH_POD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FH_Recogido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FH_Viajando")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FH_ZonaDistribucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroGuia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guias");
                });

            modelBuilder.Entity("RastreoFirplak.Domain.DocumentoEntrega", b =>
                {
                    b.HasOne("RastreoFirplak.Domain.Guia", "Guia")
                        .WithMany()
                        .HasForeignKey("GuiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guia");
                });

            modelBuilder.Entity("RastreoFirplak.Domain.DocumentoPOD", b =>
                {
                    b.HasOne("RastreoFirplak.Domain.Guia", "Guia")
                        .WithMany()
                        .HasForeignKey("GuiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guia");
                });
#pragma warning restore 612, 618
        }
    }
}
